# Generated by Django 4.2.7 on 2025-05-23 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(500)])),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)])),
                ('activity_level', models.FloatField(choices=[(1.2, 'Sedentary (little or no exercise)'), (1.375, 'Lightly active (light exercise 1-3 days/week)'), (1.55, 'Moderately active (moderate exercise 3-5 days/week)'), (1.725, 'Very active (hard exercise 6-7 days/week)'), (1.9, 'Super active (very hard exercise, physical job)')])),
                ('goal', models.CharField(choices=[('maintain', 'Maintain Weight'), ('lose', 'Lose Weight (0.5 kg/week)'), ('gain', 'Gain Weight (0.5 kg/week)')], max_length=10)),
                ('bmr', models.FloatField()),
                ('tdee', models.FloatField()),
                ('recommended_calories', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
